server:
  port: 8080
spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/changelog-master.yaml
number-generate-service:
  url: http://localhost:8081/api/v1/numbers