openapi: 3.0.3
info:
  title: Number API
  description: API для генерации уникальных номеров заказов.
  version: 1.0.0

paths:
  /api/v1/numbers:
    get:
      summary: Генерация номера заказа
      description: Генерирует уникальный номер заказа и возвращает его вместе с текущей датой.
      operationId: generateNumber
      responses:
        '200':
          description: Успешный ответ, содержащий уникальный номер заказа и текущую дату.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderNumberDto'
        '204':
          description: No Content
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorDto"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorDto"
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorDto"
        '500':
          description: Внутренняя ошибка сервера.
components:
  schemas:
    OrderNumberDto:
      type: object
      description: Класс представляет собой номер заказов в системе.
      properties:
        number:
          type: string
          description: Номер заказа.
          example: "ORD-2024-0001"
        date:
          type: string
          format: date
          description: Текущая дата.
          example: "2024-11-18"
      required:
        - number
        - date
    ErrorDto:
      type: object
      description: Сообщение об ошибке
      properties:
        errorCode:
          type: integer
          description: HTTP код
          format: int32
        errorMessage:
          type: string
          description: Сообщение
        timestamp:
          type: string
          format: date-time
          description: Время
